Create table STUDENTS(ID NUMBER(5) primary key,NAME VARCHAR2(20),MARKS NUMBER);

INSERT INTO STUDENTS VALUES(1,'Rahul',90);
INSERT INTO STUDENTS VALUES(2,'Tom',73);
INSERT INTO STUDENTS VALUES(3,'Anaya',35);

