TABLE CREATION:

CREATE TABLE STUDENT_MARK(NAME VARCHAR(15),MARK1 INT,MARK2 INT,MARK3 INT,ROLLNO INT PRIMARY KEY);

DESC STUDENT_MARK;

INSERTION:

INSERT INTO STUDENT_MARK VALUES('RAM',85,88,95,1);
INSERT INTO STUDENT_MARK VALUES('SACHIN',40,38,35,4);
INSERT INTO STUDENT_MARK VALUES('AMAL',18,24,10,5);

SELECT*FROM STUDENT_MARK;

