SET SERVEROUT ON;
DECLARE
AVEG NUMBER(2)=0;
BEGIN
FOR REC IN(SELECT NAME,(MARK1+MARK2+MARK3)/3 AS AVEG,ROLLNO FROM STUDENT_MARK)LOOP
AVEG:=REC.AVEG;
IF AVEG<40 THEN
DBMS_OUTPUT.PUT_LINE(REC.ROLLNO||''||REC.NAME||''||'NEEDS IMPROVEMENT'||
AVEG);
ELSE
DBMS_OUTPUT.PUT_LINE(REC.ROLLNO||''||REC.NAME||''||AVEG);
END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE(
);
DBMS_OUTPUT.PUT_LINE(SYSDATE||''||to_char(sysdate,'Day'));
END;
